# This is an example of a yaml configuration file for Metashape

# Path to the main flight photos
photo_path: "/mnt/ghowl/uav_raw/2022/"
multispectral: False # If RGB, set to False. If multispectral, set to True.

# Path to exports and log files
output_path: "/mnt/ghowl/metashape_outputs/log"

# Path to save project file (.psx)
project_path: "/mnt/ghowl/metaspace_projects/"

# Identifier for the run. Will also be used for output files.
run_name: "field01_rgb_run001"

#GCPs files. 
addGCGPs:
    enabled: True
    
alignPhotos: # (Metashape: alignPhotos)
    enabled: True
    downscale: 2 # Recommended: 2. How much to coarsen the photos when searching for tie points. Higher number for blurrier photos or when there are small surfces that may move between photos (such as leaves). Accepts numbers 2^x (and zero) (https://www.agisoft.com/forum/index.php?topic=11697.0).
    adaptive_fitting: True # Recommended: True. Should the camera lens model be fit at the same time as aligning photos?


buildDenseCloud: # (Metashape: buildDepthMaps, buildDenseCloud, classifyGroundPoints, and exportPoints)
    enabled: True
    ## For depth maps (buldDepthMaps)
    downscale: 2 # Recommended: 2. How much to coarsen the photos when searching for matches to build the dense cloud. For large photosets, values < 4 likely take prohibitively long. Accepts numbers 2^x (https://www.agisoft.com/forum/index.php?topic=11697.0).
    filter_mode: Metashape.MildFiltering # Recommended: Metashape.MildFiltering. How to filter the point cloud. Options are NoFiltering, MildFiltering, ModerateFiltering, AggressiveFiltering. Aggressive filtering removes detail and makes worse DEMs (at least for forest). NoFiltering takes very long. In trials, it never completed.
    reuse_depth: False # Recommended: False. Purpose unknown.
    ## For dense cloud (buildDenseCloud)
    keep_depth: False # Recommended: False. Purpose unknown.
    ## For both
    max_neighbors: 100 # Recommended: 100. Maximum number of neighboring photos to use for estimating point cloud. Higher numbers may increase accuracy but dramatically increase processing time.
    ## For ground point classification (classifyGroundPoints). Definitions here: https://www.agisoft.com/forum/index.php?topic=9328.0
    classify: True # Must be enabled if a digital terrain model (DTM) is needed either for orthomosaic or DTM export
    max_angle: 15.0 # Recommended: 15.0
    max_distance: 1.0 # Recommended: 1.0
    cell_size: 50.0 # Recommended: 50.0
    ## For dense cloud export (exportPoints)
    export: True # Whether to export dense cloud file.
    format: Metashape.PointsFormatLAS # Recommended: PointsFormatLAS. The file format to export points in.
    classes: "ALL" # Recommended: "ALL". Point classes to export. Must be a list. Or can set to "ALL" to use all points. An example of a specific class is: Metashape.PointClass.Ground
    
buildDem: # (Metashape: buildDem, exportRaster)
    enabled: True
    ## For building DEM (buildDem)
    type: "both" # Recommended: "both". Options: "DSM" or "DTM" or "both". Type of DEM to exporot (digital surface model, digital terrain model, or both).
    ## For exporting DEM (exportRaster)
    export: True # Whether to export DEM(s)
    tiff_big: True # Recommended: True. Use BigTIFF format? Required for larger projects with large DEMs
    tiff_tiled: False # Recommended: False. Use tiled TIFF? This is related to internal file architecture.
    nodata: -32767 # Recommended: -32767. Value used to represent nodata.
    tiff_overviews: True # Recommended: True. Include coarse-scale raster data in file for quick display in GIS.

buildOrthomosaic: # (Metashape: buildOrthomosaic, exportRaster)
    enabled: True
    ## For building orthomosaic (buildOrthomosaic)
    surface: "USGS" # Recommended: "USGS" (assuming a USGS DEM is available and GCPs with accurate elvevation data are being used). The surface to build the orthomosaic onto. "DTM", "DSM", "USGS", or "DTMandDSM. DTM and DSM refer to elevation models built by Metashape (buildDem step above) and stored in the project. If USGS, you must use GCPs with accurate elevations (ideally extracted from the USGS DEM).
    usgs_dem_path: "dem_usgs/dem_usgs.tif" # Path to USGS DEM for the project area. Needed if surface (parameter above) is "USGS".
    usgs_dem_crs: "EPSG::4269" # CRS of the USGS DEM. Needed if surface (parameter above) is "USGS". For sample RGB photoset, crs is 4269 (Geographic NAD83)
    blending: Metashape.MosaicBlending # Recommended: Metashape.MosaicBlending. Photo blending mode. Options include AverageBlending, MosaicBlending, MinBlending, MaxBlending, DisabledBlending
    fill_holes: True # Recommended: True. Fill holes in orthomosaic where no photo data exist by interpolating?
    refine_seamlines: True # Recommended: True. Use smart algorithm to identify photo seamlines where they will least distort.
    ## For exporting orthomosaic (exportRaster)
    export: True # Whether to export orthomosaic
    tiff_big: True # Recommended: True. Use BigTIFF format? Required for larger projects with large DEMs
    tiff_tiled: False # Recommended: False. Use tiled TIFF? This is related to internal file architecture.
    nodata: -32767 # Recommended: -32767. Value used to represent nodata.
    tiff_overviews: True # Recommended: True. Include coarse-scale raster data in file for quick display in GIS.

