name: metashape 
channels:
  - conda-forge
  - bioconda
dependencies:
 - scikit-learn
 - matplotlib
 - numpy
 - pandas
 - matplotlib
 - scipy 
 - Metashape
 - time
 - datetime
 - os
 - platform
 - glob
 - re
 - pyyaml
 - sys
 
